### ISSUE TITLE
_pickle.UnpicklingError: pickle data was truncated

### ISSUE THREAD

**Issue by HaiminZhang** [graphdeeplearning/benchmarking-gnns#40]
I got this issue when I run the following command:
 python main_superpixels_graph_classification.py --dataset CIFAR10 --gpu_id 3 --see
d 41 --config configs/superpixels_graph_classification_GAT_CIFAR10_100k.json

cuda available with GPU: GeForce GTX 1080
[I] Loading dataset CIFAR10...
Traceback (most recent call last):
  File "main_superpixels_graph_classification.py", line 430, in <module>
    main()
  File "main_superpixels_graph_classification.py", line 314, in main
    dataset = LoadData(DATASET_NAME)
  File "/mnt/DISK10T/zhanghm/benchmarkingGNN/benchmarking-gnns/data/data.py", line 21, in LoadData
    return SuperPixDataset(DATASET_NAME)
  File "/mnt/DISK10T/zhanghm/benchmarkingGNN/benchmarking-gnns/data/superpixels.py", line 272, in __init__
    f = pickle.load(f)
_pickle.UnpicklingError: pickle data was truncated

Could assistance be provided for addressing this issue?

**Comment by HaiminZhang** [comment]
This issue is caused by curl.
I used the Dropbox app to download the file and this issue is solved.

**Comment by vijaydwivedi75** [comment]
Thanks and great its solved.

Incomplete pickle files often result in the error you encountered.
