### ISSUE TITLE
How to fix this bug?

### ISSUE THREAD

**Issue by BodongDu** [graphdeeplearning/benchmarking-gnns#85]
When I run python main_SBMs_node_classification.py  --dataset SBM_CLUSTER --gpu_id 0 --seed 41 --config 'configs/SBMs_node_clustering_MLP_CLUSTER_100k.json'
It comes with the errors:
cuda available with GPU: NVIDIA GeForce RTX 3090
[I] Loading dataset SBM_CLUSTER...
Traceback (most recent call last):
  File "/home/zbh/whd/benchmarking-gnns-master/main_SBMs_node_classification.py", line 428, in <module>
    main()    
  File "/home/zbh/whd/benchmarking-gnns-master/main_SBMs_node_classification.py", line 318, in main
    dataset = LoadData(DATASET_NAME)
  File "/home/zbh/whd/benchmarking-gnns-master/data/data.py", line 38, in LoadData
    return SBMsDataset(DATASET_NAME)
  File "/home/zbh/whd/benchmarking-gnns-master/data/SBMs.py", line 160, in __init__
    f = pickle.load(f)
AttributeError: Can't get attribute 'DGLHeteroGraph' on <module 'dgl.heterograph' from '/home/zbh/.conda/envs/dgl/lib/python3.9/site-packages/dgl/heterograph.py'>
My environment: dgl 1.1.2+cu118 cuda 12.2. I really need help, thx.

**Comment by BodongDu** [comment]
I solve it by reproducing the datasets.
